ERROR - 2025-10-05 14:39:06 --> mysqli_sql_exception: Duplicate entry 'admin@example.com' for key 'email' in C:\xampp\htdocs\ITE311-ZAMBRONA\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\ITE311-ZAMBRONA\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp\htdocs\ITE311-ZAMBRONA\system\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp\htdocs\ITE311-ZAMBRONA\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp\htdocs\ITE311-ZAMBRONA\system\Database\BaseBuilder.php(1841): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', NULL, false)
#4 C:\xampp\htdocs\ITE311-ZAMBRONA\system\Database\BaseBuilder.php(2230): CodeIgniter\Database\BaseBuilder->batchExecute('_insertBatch', 100)
#5 C:\xampp\htdocs\ITE311-ZAMBRONA\app\Database\Seeds\UserSeeder.php(54): CodeIgniter\Database\BaseBuilder->insertBatch(Array)
#6 C:\xampp\htdocs\ITE311-ZAMBRONA\system\Database\Seeder.php(149): App\Database\Seeds\UserSeeder->run()
#7 C:\xampp\htdocs\ITE311-ZAMBRONA\system\Commands\Database\Seed.php(79): CodeIgniter\Database\Seeder->call('App\\Database\\Se...')
#8 C:\xampp\htdocs\ITE311-ZAMBRONA\system\CLI\Commands.php(74): CodeIgniter\Commands\Database\Seed->run(Array)
#9 C:\xampp\htdocs\ITE311-ZAMBRONA\system\CLI\Console.php(47): CodeIgniter\CLI\Commands->run('db:seed', Array)
#10 C:\xampp\htdocs\ITE311-ZAMBRONA\system\Boot.php(388): CodeIgniter\CLI\Console->run()
#11 C:\xampp\htdocs\ITE311-ZAMBRONA\system\Boot.php(133): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
#12 C:\xampp\htdocs\ITE311-ZAMBRONA\spark(87): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
#13 {main}
ERROR - 2025-10-05 14:41:06 --> mysqli_sql_exception: Unknown column 'c.title' in 'field list' in C:\xampp\htdocs\ITE311-ZAMBRONA\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\ITE311-ZAMBRONA\system\Database\MySQLi\Connection.php(327): mysqli->query('SELECT `c`.`id`...', 0)
#1 C:\xampp\htdocs\ITE311-ZAMBRONA\system\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `c`.`id`...')
#2 C:\xampp\htdocs\ITE311-ZAMBRONA\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `c`.`id`...')
#3 C:\xampp\htdocs\ITE311-ZAMBRONA\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT `c`.`id`...', Array, false)
#4 C:\xampp\htdocs\ITE311-ZAMBRONA\app\Controllers\Auth.php(217): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\ITE311-ZAMBRONA\system\CodeIgniter.php(933): App\Controllers\Auth->dashboard()
#6 C:\xampp\htdocs\ITE311-ZAMBRONA\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#7 C:\xampp\htdocs\ITE311-ZAMBRONA\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\ITE311-ZAMBRONA\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\ITE311-ZAMBRONA\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 C:\xampp\htdocs\ITE311-ZAMBRONA\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 {main}
ERROR - 2025-10-05 14:41:06 --> mysqli_sql_exception: Table 'lms_zambrona.assignments' doesn't exist in C:\xampp\htdocs\ITE311-ZAMBRONA\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\ITE311-ZAMBRONA\system\Database\MySQLi\Connection.php(327): mysqli->query('SELECT `a`.`id`...', 0)
#1 C:\xampp\htdocs\ITE311-ZAMBRONA\system\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `a`.`id`...')
#2 C:\xampp\htdocs\ITE311-ZAMBRONA\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `a`.`id`...')
#3 C:\xampp\htdocs\ITE311-ZAMBRONA\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT `a`.`id`...', Array, false)
#4 C:\xampp\htdocs\ITE311-ZAMBRONA\app\Controllers\Auth.php(229): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\ITE311-ZAMBRONA\system\CodeIgniter.php(933): App\Controllers\Auth->dashboard()
#6 C:\xampp\htdocs\ITE311-ZAMBRONA\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#7 C:\xampp\htdocs\ITE311-ZAMBRONA\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\ITE311-ZAMBRONA\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\ITE311-ZAMBRONA\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 C:\xampp\htdocs\ITE311-ZAMBRONA\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 {main}
ERROR - 2025-10-05 14:41:06 --> mysqli_sql_exception: Table 'lms_zambrona.grades' doesn't exist in C:\xampp\htdocs\ITE311-ZAMBRONA\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\ITE311-ZAMBRONA\system\Database\MySQLi\Connection.php(327): mysqli->query('SELECT `g`.`sco...', 0)
#1 C:\xampp\htdocs\ITE311-ZAMBRONA\system\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `g`.`sco...')
#2 C:\xampp\htdocs\ITE311-ZAMBRONA\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `g`.`sco...')
#3 C:\xampp\htdocs\ITE311-ZAMBRONA\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT `g`.`sco...', Array, false)
#4 C:\xampp\htdocs\ITE311-ZAMBRONA\app\Controllers\Auth.php(242): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\ITE311-ZAMBRONA\system\CodeIgniter.php(933): App\Controllers\Auth->dashboard()
#6 C:\xampp\htdocs\ITE311-ZAMBRONA\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#7 C:\xampp\htdocs\ITE311-ZAMBRONA\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\ITE311-ZAMBRONA\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\ITE311-ZAMBRONA\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 C:\xampp\htdocs\ITE311-ZAMBRONA\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 {main}
ERROR - 2025-10-05 14:51:46 --> mysqli_sql_exception: Table 'lms_zambrona.users' doesn't exist in C:\xampp\htdocs\ITE311-ZAMBRONA\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\ITE311-ZAMBRONA\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp\htdocs\ITE311-ZAMBRONA\system\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp\htdocs\ITE311-ZAMBRONA\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp\htdocs\ITE311-ZAMBRONA\system\Database\BaseBuilder.php(1841): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', NULL, false)
#4 C:\xampp\htdocs\ITE311-ZAMBRONA\system\Database\BaseBuilder.php(2230): CodeIgniter\Database\BaseBuilder->batchExecute('_insertBatch', 100)
#5 C:\xampp\htdocs\ITE311-ZAMBRONA\app\Database\Seeds\UserSeeder.php(49): CodeIgniter\Database\BaseBuilder->insertBatch(Array)
#6 C:\xampp\htdocs\ITE311-ZAMBRONA\system\Database\Seeder.php(149): App\Database\Seeds\UserSeeder->run()
#7 C:\xampp\htdocs\ITE311-ZAMBRONA\system\Commands\Database\Seed.php(79): CodeIgniter\Database\Seeder->call('App\\Database\\Se...')
#8 C:\xampp\htdocs\ITE311-ZAMBRONA\system\CLI\Commands.php(74): CodeIgniter\Commands\Database\Seed->run(Array)
#9 C:\xampp\htdocs\ITE311-ZAMBRONA\system\CLI\Console.php(47): CodeIgniter\CLI\Commands->run('db:seed', Array)
#10 C:\xampp\htdocs\ITE311-ZAMBRONA\system\Boot.php(388): CodeIgniter\CLI\Console->run()
#11 C:\xampp\htdocs\ITE311-ZAMBRONA\system\Boot.php(133): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
#12 C:\xampp\htdocs\ITE311-ZAMBRONA\spark(87): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
#13 {main}
ERROR - 2025-10-05 14:53:01 --> mysqli_sql_exception: Unknown column 'teacher_id' in 'where clause' in C:\xampp\htdocs\ITE311-ZAMBRONA\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\ITE311-ZAMBRONA\system\Database\MySQLi\Connection.php(327): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\xampp\htdocs\ITE311-ZAMBRONA\system\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\xampp\htdocs\ITE311-ZAMBRONA\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\xampp\htdocs\ITE311-ZAMBRONA\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\ITE311-ZAMBRONA\app\Controllers\Auth.php(189): CodeIgniter\Database\BaseBuilder->get(10)
#5 C:\xampp\htdocs\ITE311-ZAMBRONA\system\CodeIgniter.php(933): App\Controllers\Auth->dashboard()
#6 C:\xampp\htdocs\ITE311-ZAMBRONA\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#7 C:\xampp\htdocs\ITE311-ZAMBRONA\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\ITE311-ZAMBRONA\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\ITE311-ZAMBRONA\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 C:\xampp\htdocs\ITE311-ZAMBRONA\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 {main}
ERROR - 2025-10-05 14:53:01 --> mysqli_sql_exception: Unknown column 'student_name' in 'field list' in C:\xampp\htdocs\ITE311-ZAMBRONA\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\ITE311-ZAMBRONA\system\Database\MySQLi\Connection.php(327): mysqli->query('SELECT `student...', 0)
#1 C:\xampp\htdocs\ITE311-ZAMBRONA\system\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `student...')
#2 C:\xampp\htdocs\ITE311-ZAMBRONA\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `student...')
#3 C:\xampp\htdocs\ITE311-ZAMBRONA\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT `student...', Array, false)
#4 C:\xampp\htdocs\ITE311-ZAMBRONA\app\Controllers\Auth.php(200): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\ITE311-ZAMBRONA\system\CodeIgniter.php(933): App\Controllers\Auth->dashboard()
#6 C:\xampp\htdocs\ITE311-ZAMBRONA\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#7 C:\xampp\htdocs\ITE311-ZAMBRONA\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\ITE311-ZAMBRONA\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\ITE311-ZAMBRONA\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 C:\xampp\htdocs\ITE311-ZAMBRONA\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 {main}
ERROR - 2025-10-05 14:58:17 --> mysqli_sql_exception: Unknown column 'teacher_id' in 'where clause' in C:\xampp\htdocs\ITE311-ZAMBRONA\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\ITE311-ZAMBRONA\system\Database\MySQLi\Connection.php(327): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\xampp\htdocs\ITE311-ZAMBRONA\system\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\xampp\htdocs\ITE311-ZAMBRONA\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\xampp\htdocs\ITE311-ZAMBRONA\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\ITE311-ZAMBRONA\app\Controllers\Auth.php(189): CodeIgniter\Database\BaseBuilder->get(10)
#5 C:\xampp\htdocs\ITE311-ZAMBRONA\system\CodeIgniter.php(933): App\Controllers\Auth->dashboard()
#6 C:\xampp\htdocs\ITE311-ZAMBRONA\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#7 C:\xampp\htdocs\ITE311-ZAMBRONA\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\ITE311-ZAMBRONA\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\ITE311-ZAMBRONA\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 C:\xampp\htdocs\ITE311-ZAMBRONA\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 {main}
ERROR - 2025-10-05 14:58:17 --> mysqli_sql_exception: Unknown column 'student_name' in 'field list' in C:\xampp\htdocs\ITE311-ZAMBRONA\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\ITE311-ZAMBRONA\system\Database\MySQLi\Connection.php(327): mysqli->query('SELECT `student...', 0)
#1 C:\xampp\htdocs\ITE311-ZAMBRONA\system\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `student...')
#2 C:\xampp\htdocs\ITE311-ZAMBRONA\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `student...')
#3 C:\xampp\htdocs\ITE311-ZAMBRONA\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT `student...', Array, false)
#4 C:\xampp\htdocs\ITE311-ZAMBRONA\app\Controllers\Auth.php(200): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\ITE311-ZAMBRONA\system\CodeIgniter.php(933): App\Controllers\Auth->dashboard()
#6 C:\xampp\htdocs\ITE311-ZAMBRONA\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#7 C:\xampp\htdocs\ITE311-ZAMBRONA\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\ITE311-ZAMBRONA\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\ITE311-ZAMBRONA\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 C:\xampp\htdocs\ITE311-ZAMBRONA\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 {main}
ERROR - 2025-10-05 14:58:24 --> mysqli_sql_exception: Unknown column 'c.title' in 'field list' in C:\xampp\htdocs\ITE311-ZAMBRONA\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\ITE311-ZAMBRONA\system\Database\MySQLi\Connection.php(327): mysqli->query('SELECT `c`.`id`...', 0)
#1 C:\xampp\htdocs\ITE311-ZAMBRONA\system\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `c`.`id`...')
#2 C:\xampp\htdocs\ITE311-ZAMBRONA\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `c`.`id`...')
#3 C:\xampp\htdocs\ITE311-ZAMBRONA\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT `c`.`id`...', Array, false)
#4 C:\xampp\htdocs\ITE311-ZAMBRONA\app\Controllers\Auth.php(217): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\ITE311-ZAMBRONA\system\CodeIgniter.php(933): App\Controllers\Auth->dashboard()
#6 C:\xampp\htdocs\ITE311-ZAMBRONA\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#7 C:\xampp\htdocs\ITE311-ZAMBRONA\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\ITE311-ZAMBRONA\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\ITE311-ZAMBRONA\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 C:\xampp\htdocs\ITE311-ZAMBRONA\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 {main}
ERROR - 2025-10-05 14:58:24 --> mysqli_sql_exception: Table 'lms_zambrona.assignments' doesn't exist in C:\xampp\htdocs\ITE311-ZAMBRONA\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\ITE311-ZAMBRONA\system\Database\MySQLi\Connection.php(327): mysqli->query('SELECT `a`.`id`...', 0)
#1 C:\xampp\htdocs\ITE311-ZAMBRONA\system\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `a`.`id`...')
#2 C:\xampp\htdocs\ITE311-ZAMBRONA\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `a`.`id`...')
#3 C:\xampp\htdocs\ITE311-ZAMBRONA\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT `a`.`id`...', Array, false)
#4 C:\xampp\htdocs\ITE311-ZAMBRONA\app\Controllers\Auth.php(229): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\ITE311-ZAMBRONA\system\CodeIgniter.php(933): App\Controllers\Auth->dashboard()
#6 C:\xampp\htdocs\ITE311-ZAMBRONA\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#7 C:\xampp\htdocs\ITE311-ZAMBRONA\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\ITE311-ZAMBRONA\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\ITE311-ZAMBRONA\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 C:\xampp\htdocs\ITE311-ZAMBRONA\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 {main}
ERROR - 2025-10-05 14:58:24 --> mysqli_sql_exception: Table 'lms_zambrona.grades' doesn't exist in C:\xampp\htdocs\ITE311-ZAMBRONA\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\ITE311-ZAMBRONA\system\Database\MySQLi\Connection.php(327): mysqli->query('SELECT `g`.`sco...', 0)
#1 C:\xampp\htdocs\ITE311-ZAMBRONA\system\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `g`.`sco...')
#2 C:\xampp\htdocs\ITE311-ZAMBRONA\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `g`.`sco...')
#3 C:\xampp\htdocs\ITE311-ZAMBRONA\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT `g`.`sco...', Array, false)
#4 C:\xampp\htdocs\ITE311-ZAMBRONA\app\Controllers\Auth.php(242): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\ITE311-ZAMBRONA\system\CodeIgniter.php(933): App\Controllers\Auth->dashboard()
#6 C:\xampp\htdocs\ITE311-ZAMBRONA\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#7 C:\xampp\htdocs\ITE311-ZAMBRONA\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\ITE311-ZAMBRONA\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\ITE311-ZAMBRONA\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 C:\xampp\htdocs\ITE311-ZAMBRONA\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 {main}
ERROR - 2025-10-05 15:42:43 --> mysqli_sql_exception: Unknown column 'c.title' in 'field list' in C:\xampp\htdocs\ITE311-ZAMBRONA\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\ITE311-ZAMBRONA\system\Database\MySQLi\Connection.php(327): mysqli->query('SELECT `c`.`id`...', 0)
#1 C:\xampp\htdocs\ITE311-ZAMBRONA\system\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `c`.`id`...')
#2 C:\xampp\htdocs\ITE311-ZAMBRONA\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `c`.`id`...')
#3 C:\xampp\htdocs\ITE311-ZAMBRONA\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT `c`.`id`...', Array, false)
#4 C:\xampp\htdocs\ITE311-ZAMBRONA\app\Controllers\Auth.php(217): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\ITE311-ZAMBRONA\system\CodeIgniter.php(933): App\Controllers\Auth->dashboard()
#6 C:\xampp\htdocs\ITE311-ZAMBRONA\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#7 C:\xampp\htdocs\ITE311-ZAMBRONA\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\ITE311-ZAMBRONA\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\ITE311-ZAMBRONA\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 C:\xampp\htdocs\ITE311-ZAMBRONA\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 {main}
ERROR - 2025-10-05 15:42:43 --> mysqli_sql_exception: Table 'lms_zambrona.assignments' doesn't exist in C:\xampp\htdocs\ITE311-ZAMBRONA\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\ITE311-ZAMBRONA\system\Database\MySQLi\Connection.php(327): mysqli->query('SELECT `a`.`id`...', 0)
#1 C:\xampp\htdocs\ITE311-ZAMBRONA\system\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `a`.`id`...')
#2 C:\xampp\htdocs\ITE311-ZAMBRONA\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `a`.`id`...')
#3 C:\xampp\htdocs\ITE311-ZAMBRONA\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT `a`.`id`...', Array, false)
#4 C:\xampp\htdocs\ITE311-ZAMBRONA\app\Controllers\Auth.php(229): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\ITE311-ZAMBRONA\system\CodeIgniter.php(933): App\Controllers\Auth->dashboard()
#6 C:\xampp\htdocs\ITE311-ZAMBRONA\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#7 C:\xampp\htdocs\ITE311-ZAMBRONA\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\ITE311-ZAMBRONA\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\ITE311-ZAMBRONA\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 C:\xampp\htdocs\ITE311-ZAMBRONA\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 {main}
ERROR - 2025-10-05 15:42:43 --> mysqli_sql_exception: Table 'lms_zambrona.grades' doesn't exist in C:\xampp\htdocs\ITE311-ZAMBRONA\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\ITE311-ZAMBRONA\system\Database\MySQLi\Connection.php(327): mysqli->query('SELECT `g`.`sco...', 0)
#1 C:\xampp\htdocs\ITE311-ZAMBRONA\system\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `g`.`sco...')
#2 C:\xampp\htdocs\ITE311-ZAMBRONA\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `g`.`sco...')
#3 C:\xampp\htdocs\ITE311-ZAMBRONA\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT `g`.`sco...', Array, false)
#4 C:\xampp\htdocs\ITE311-ZAMBRONA\app\Controllers\Auth.php(242): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\ITE311-ZAMBRONA\system\CodeIgniter.php(933): App\Controllers\Auth->dashboard()
#6 C:\xampp\htdocs\ITE311-ZAMBRONA\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#7 C:\xampp\htdocs\ITE311-ZAMBRONA\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\ITE311-ZAMBRONA\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\ITE311-ZAMBRONA\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 C:\xampp\htdocs\ITE311-ZAMBRONA\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 {main}
